import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Template } from '@/types';
import { realApi } from '@/lib/api/real-api';

interface TemplatesState {
    templates: Template[];
    isLoading: boolean;
    searchQuery: string;
    filterCategory: string | null;

    // Actions
    fetchTemplates: () => Promise<void>;
    setSearchQuery: (query: string) => void;
    setFilterCategory: (category: string | null) => void;
    addTemplate: (template: Omit<Template, 'id' | 'status' | 'lastUpdated' | 'usageCount'>) => Promise<void>;
    updateTemplate: (id: string, updates: Partial<Template>) => Promise<void>;
}

export const useTemplatesStore = create<TemplatesState>()(
    persist(
        (set, get) => ({
            templates: [],
            isLoading: false,
            searchQuery: '',
            filterCategory: null,

            fetchTemplates: async () => {
                set({ isLoading: true });
                try {
                    const templates = await realApi.templates.getTemplates();
                    set({ templates, isLoading: false });
                } catch (error) {
                    console.error("Failed to fetch templates:", error);
                    set({ isLoading: false });
                }
            },

            setSearchQuery: (query) => set({ searchQuery: query }),
            setFilterCategory: (category) => set({ filterCategory: category }),

            addTemplate: async (templateData) => {
                try {
                    // Prepare template for API
                    const newTemplatePayload = {
                        ...templateData,
                        // id is generated by backend
                        id: "",
                        status: 'pending',
                        lastUpdated: new Date().toISOString(),
                        usageCount: 0
                    } as Template;

                    const created = await realApi.templates.createTemplate(newTemplatePayload);
                    set(state => ({
                        templates: [...state.templates, created]
                    }));
                } catch (error) {
                    console.error("Failed to create template:", error);
                }
            },

            updateTemplate: async (id, updates) => {
                try {
                    const updated = await realApi.templates.updateTemplate(id, updates);
                    set(state => ({
                        templates: state.templates.map(t =>
                            t.id === id
                                ? { ...t, ...updated, lastUpdated: new Date().toISOString() }
                                : t
                        )
                    }));
                } catch (error) {
                    console.error("Failed to update template:", error);
                }
            },
        }),
        {
            name: 'templates-storage',
            partialize: (state) => ({
                templates: state.templates
            })
        }
    )
);
